export const UI_START_LOADING = 'ui-start-loading';
export const UI_STOP_LOADING = 'ui-stop-loading';

export const SET_LANGUAGE = 'SET_LANGUAGE';

export const SET_TOKEN = 'SET_TOKEN';

export const SET_USER = 'SET_USER';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_SUB_CATEGORIES = 'SET_SUB_CATEGORIES';
export const SET_CATEGORY_ITEMS = 'SET_CATEGORY_ITEMS';
export const SET_CATEGORY_PRODUCTS = 'SET_CATEGORY_PRODUCTS';
export const SET_VEIL = 'SET_VEIL';

export const SET_BESTSELLERS = 'SET_BESTSELLERS';
export const SET_ALL_BESTSELLERS = 'SET_ALL_BESTSELLERS';
export const SET_LATEST = 'SET_LATEST';
export const SET_ALL_LATEST = 'SET_ALL_LATEST';
export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS';
export const SET_BANNERS = 'SET_BANNERS';

export const SET_CART = 'SET_CART';

export const SET_WISHLIST = 'SET_WISHLIST';

export const SET_SHIIPING_ADDRESS = 'SET_SHIIPING_ADDRESS';
export const SET_SHIIPING_ADDRESS_DONE = 'SET_SHIIPING_ADDRESS_DONE';
export const SET_SHIIPING_METHOD = 'SET_SHIIPING_METHOD';
export const SET_ORDER_SUMMARY = 'SET_ORDER_SUMMARY';
export const SET_USER_NEW_ADDRESS = 'SET_USER_NEW_ADDRESS';
export const SET_ORDER_CONFIRMED = 'SET_ORDER_CONFIRMED';

export const SET_ORDERS = 'SET_ORDERS';
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS';
export const SET_STATUSES = 'SET_STATUSES';